### PR TITLE
Fix/various bugfixes

### PR DESCRIPTION
**Pull request by mikemonteith**

### CODE REVIEW

**Review by beseven — APPROVED** [review]
LOTM!

**Comment by beseven** [comment]
@gareth, could you test your changes on `betahealth` with this branch please? If all ok, please merge!

**Comment by gareth** [comment]
I'm probably not the Gareth you meant to tag, so there's another Gareth out there somewhere who still needs to see your notification.

**Comment by gareth** [comment]
Looks like @Garethrehal

**Review by beseven — APPROVED** [review]
LOTM!

**Pull request merged**
